context:
  version: "0.11.6"

package:
  name: civet
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@danielx/civet/-/civet-${{ version }}.tgz
  sha256: 1767336173a303882224860ab441ac504c23f2b62b3831cd77b341e7ef423940

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - civet --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A TypeScript superset that favors more types and less typing
  homepage: https://github.com/DanielXMoore/civet
  repository: https://github.com/DanielXMoore/civet

extra:
  recipe-maintainers:
    - danielnachun
