context:
  version: "0.11.8"

package:
  name: civet
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@danielx/civet/-/civet-${{ version }}.tgz
  sha256: ba4f0356518647baeee0dcc18b62782f5965c59fe40cfc44e7ba7fed3bd5c3fe

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - civet --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A TypeScript superset that favors more types and less typing
  homepage: https://github.com/DanielXMoore/civet
  repository: https://github.com/DanielXMoore/civet

extra:
  recipe-maintainers:
    - danielnachun
